### PR TITLE
Prepare for release 1.1.0

### PR DESCRIPTION
**Pull request by romulogoncalves**
Changes to prepare for release.
It should only be merged after PR #11

### CODE REVIEW

**Comment by romulogoncalves** [comment]
@sverhoeven ready to be merged :)
Then I do a release and I have already the package ready to submit to pypi.
For the release I only need to add to the changelog what were the improvements, right?

**Comment by romulogoncalves** [comment]
@sverhoeven release draft created. Only questions is about the assets, what should be attached? Just a zip and a tar of the main branch? Is that done manually or is there an option in GitHub to do it?

**Comment by sverhoeven** [comment]
The following steps need to be done

* [x]  include link to PyPI in README
* [x] Update installation instructions to `pip install dask-cassandra-loader` instead of clone. Clone is lib development
* [x] add [draft release description](https://github.com/NLeSC/dask-cassandra-loader/releases/tag/untagged-9c32499d881e76d4d6be) to the [CHANGELOG](https://github.com/NLeSC/dask-cassandra-loader/blob/master/CHANGELOG.rst)
* [x] Publish draft release, the source code artifacts of the GitHub release are automatically generated by GitHub. You don't need to upload binaries here as they will be hosted on PyPI
* [x] Create new version on PyPIwith 

    ```shell
   pip install wheel twine
   python setup.py sdist bdist_wheel
   twine upload dist/*
   ```

**Review by sverhoeven — APPROVED** [review]
Looking good

**Comment by romulogoncalves** [comment]
@sverhoeven since the draft release is on the Master, do not we have first to merge this pull request and then publish the release? 

The rest is done. I think we can merge.

**Comment by sverhoeven** [comment]
Yep, after this PR is merged the GitHub release must be made.

**Pull request merged**
